import 'package:flutter/material.dart';

class LandingPageTheme {
  final Color primary;
  final Color secondary;
  final Color background;
  final Color textPrimary;
  final Color textSecondary;
  final String name;
  final String? defaultFont; // New: Assign a default font per theme
  final String? globalBgImageUrl; // New: Global Page Background Image
  final String? globalBgColorHex; // New: Global Page Background Color
  final String? category;
  final String? description;

  const LandingPageTheme({
    required this.primary,
    required this.secondary,
    required this.background,
    required this.textPrimary,
    required this.textSecondary,
    required this.name,
    this.defaultFont,
    this.globalBgImageUrl,
    this.globalBgColorHex,
    this.category,
    this.description,
  });

  Map<String, dynamic> toJson() => {
    'primary': primary.toARGB32(),
    'secondary': secondary.toARGB32(),
    'background': background.toARGB32(),
    'textPrimary': textPrimary.toARGB32(),
    'textSecondary': textSecondary.toARGB32(),
    'name': name,
    'defaultFont': defaultFont,
    'globalBgImageUrl': globalBgImageUrl,
    'globalBgColorHex': globalBgColorHex,
    'category': category,
    'description': description,
  };

  factory LandingPageTheme.fromJson(Map<String, dynamic> json) {
    return LandingPageTheme(
      primary: Color(json['primary'] ?? 0xFF6366F1),
      secondary: Color(json['secondary'] ?? 0xFF06B6D4),
      background: Color(json['background'] ?? 0xFF0F172A),
      textPrimary: Color(json['textPrimary'] ?? 0xFFF8FAFC),
      textSecondary: Color(json['textSecondary'] ?? 0xFF94A3B8),
      name: json['name'] ?? 'Default Dark',
      defaultFont: json['defaultFont'],
      globalBgImageUrl: json['globalBgImageUrl'],
      globalBgColorHex: json['globalBgColorHex'],
      category: json['category'],
      description: json['description'],
    );
  }

  LandingPageTheme copyWith({
    Color? primary,
    Color? secondary,
    Color? background,
    Color? textPrimary,
    Color? textSecondary,
    String? name,
    String? defaultFont,
    String? globalBgImageUrl,
    String? globalBgColorHex,
    String? category,
    String? description,
    bool clearBgImage = false,
    bool clearBgColor = false,
  }) {
    return LandingPageTheme(
      primary: primary ?? this.primary,
      secondary: secondary ?? this.secondary,
      background: background ?? this.background,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      name: name ?? this.name,
      defaultFont: defaultFont ?? this.defaultFont,
      globalBgImageUrl: clearBgImage ? null : (globalBgImageUrl ?? this.globalBgImageUrl),
      globalBgColorHex: clearBgColor ? null : (globalBgColorHex ?? this.globalBgColorHex),
      category: category ?? this.category,
      description: description ?? this.description,
    );
  }

  static const List<Map<String, String>> availableFonts = [
    {'family': 'Cairo', 'category': 'تقني وعصري / Modern Tech', 'desc': 'خط عصري وحاد يناسب واجهات المستخدم والمنصات التقنية والمتاجر.'},
    {'family': 'Tajawal', 'category': 'قراءة ومحتوى / Reading', 'desc': 'خط نقي وسهل القراءة جداً، مثالي للمدونات والمقالات والنصوص الطويلة.'},
    {'family': 'Almarai', 'category': 'رسمي واحترافي / Professional', 'desc': 'خط احترافي وهادئ ممتاز للشركات والمؤسسات والـ SaaS.'},
    {'family': 'Changa', 'category': 'عناوين بارزة / Bold Display', 'desc': 'خط عريض ومميز للإعلانات والعناوين الكبيرة لجذب الانتباه.'},
    {'family': 'Readex Pro', 'category': 'هندسي حديث / Geometric', 'desc': 'خط هندسي متطور مناسب للمنتجات الرقمية والتطبيقات الحديثة.'},
    {'family': 'Amiri', 'category': 'كلاسيكي وأصيل / Classic', 'desc': 'خط عربي أصيل ورسمي (نسخ) للجرائد، الكتب، والمحتوى الكلاسيكي.'},
    {'family': 'Lalezar', 'category': 'مرح وترفيه / Fun Display', 'desc': 'خط عريض ومرح مناسب جداً للفعاليات، الألعاب، والأنشطة الترفيهية.'},
    {'family': 'Zain', 'category': 'إبداعي وشخصي / Creative', 'desc': 'خط إبداعي وحديث ممتاز للمحافظ الشخصية، المصممين، والمبدعين.'},
    {'family': 'Alexandria', 'category': 'أعمال وتجارة / Business', 'desc': 'خط هندسي متزن ورسمي بقوة، مناسب جداً للمتاجر الإلكترونية والشركات.'},
    {'family': 'El Messiri', 'category': 'فخامة وأناقة / Luxury', 'desc': 'خط أنيق جداً بلمسة تقليدية رائعة للعلامات التجارية الفاخرة والعقارات.'},
    {'family': 'Aref Ruqaa', 'category': 'فني وتراثي / Artistic', 'desc': 'خط مستوحى من خط الرقعة الكلاسيكي، يضيف لمسة فنية وتراثية جميلة.'},
    {'family': 'Reem Kufi', 'category': 'ثقافي وهندسي / Cultural', 'desc': 'خط كوفي هندسي جذاب يعطي طابعاً ثقافياً عربياً مميزاً للتصميم.'},
    {'family': 'Lemonada', 'category': 'لطيف وشبابي / Friendly', 'desc': 'خط لطيف وغير رسمي (Casual) مناسب للأنشطة الشبابية والهوايات.'},
    {'family': 'Roboto', 'category': 'عالمي / Global Standard', 'desc': 'الخط الافتراضي لأنظمة أندرويد، عملي وسريع القراءة بأي حجم.'},
  ];

  static List<LandingPageTheme> get palettes => [
    const LandingPageTheme(
      name: 'Lux-Earth',
      category: 'التجارة / متجر',
      description: 'ألوان ترابية دافئة توحي بالفخامة والثقة.',
      defaultFont: 'Tajawal',
      primary: Color(0xFF5E3023),
      secondary: Color(0xFFA86A24),
      background: Color(0xFFFEFAE0),
      textPrimary: Color(0xFF281510),
      textSecondary: Color(0xFF5E3023),
    ),
    const LandingPageTheme(
      name: 'Fresh Mint',
      category: 'مطاعم / صحة',
      description: 'ألوان هادئة ومنعشة تناسب المحتوى الغذائي والصحي.',
      defaultFont: 'Almarai',
      primary: Color(0xFF064E3B),
      secondary: Color(0xFF10B981),
      background: Color(0xFFECFDF5),
      textPrimary: Color(0xFF064E3B),
      textSecondary: Color(0xFF047857),
    ),
    const LandingPageTheme(
      name: 'Tech Indigo',
      category: 'تكنولوجيا / SaaS',
      description: 'نمط عصري احترافي للشركات التقنية والبرمجيات.',
      defaultFont: 'Roboto',
      primary: Color(0xFF4338CA),
      secondary: Color(0xFF818CF8),
      background: Color(0xFFEEF2FF),
      textPrimary: Color(0xFF312E81),
      textSecondary: Color(0xFF4338CA),
    ),
    const LandingPageTheme(
      name: 'Royal Gold',
      category: 'عقارات / فخامة',
      description: 'مزيج الكحلي والذهبي لإعطاء طابع ملكي وراقي.',
      defaultFont: 'Amiri',
      primary: Color(0xFF0F1E36),
      secondary: Color(0xFFD4AF37),
      background: Color(0xFFF4F6F9),
      textPrimary: Color(0xFF0F1E36),
      textSecondary: Color(0xFF5A6678),
    ),
    const LandingPageTheme(
      name: 'Stadium Neon',
      category: 'ترفيه / رياضة',
      description: 'تباين عالي وألوان صارخة للفعاليات والأنشطة الليلية.',
      defaultFont: 'Oswald',
      primary: Color(0xFF00d084),
      secondary: Color(0xFF3E96F4),
      background: Color(0xFF000000),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB0B0B0),
    ),
    const LandingPageTheme(
      name: 'Butter & Sky',
      category: 'شخصي / إبداعي',
      description: 'ألوان لطيفة ومشرقة تناسب معرض الأعمال الشخصي.',
      defaultFont: 'Montserrat',
      primary: Color(0xFF31393C),
      secondary: Color(0xFFCAE4DB),
      background: Color(0xFFFFF4D6),
      textPrimary: Color(0xFF31393C),
      textSecondary: Color(0xFF5A666B),
    ),
    const LandingPageTheme(
      name: 'Minimal Slate',
      category: 'عام / بسيط',
      description: 'تصميم بسيط ونظيف يركز على المحتوى.',
      defaultFont: 'Open Sans',
      primary: Color(0xFF334155),
      secondary: Color(0xFF64748B),
      background: Color(0xFFF8FAFC),
      textPrimary: Color(0xFF0F172A),
      textSecondary: Color(0xFF475569),
    ),
    const LandingPageTheme(
      name: 'Deep Forest',
      category: 'طبيعة / تعليم',
      description: 'ألوان داكنة مستوحاة من الطبيعة تعطي انطباعاً بالهدوء.',
      defaultFont: 'Almarai',
      primary: Color(0xFF14532D),
      secondary: Color(0xFF22C55E),
      background: Color(0xFFF0FDF4),
      textPrimary: Color(0xFF064E3B),
      textSecondary: Color(0xFF14532D),
    ),
    const LandingPageTheme(
      name: 'Coral Dream',
      category: 'جمال / تجميل',
      description: 'ألوان أنثوية وناعمة لخدمات التجميل والأناقة.',
      defaultFont: 'Playfair Display',
      primary: Color(0xFF991B1B),
      secondary: Color(0xFFF87171),
      background: Color(0xFFFEF2F2),
      textPrimary: Color(0xFF7F1D1D),
      textSecondary: Color(0xFF991B1B),
    ),
    const LandingPageTheme(
      name: 'Midnight Ocean',
      category: 'شركات / رسمي',
      description: 'أزرق داكن رسمي يوحي بالاستقرار والاحترافية.',
      defaultFont: 'Changa',
      primary: Color(0xFF1E3A8A),
      secondary: Color(0xFF3B82F6),
      background: Color(0xFFEFF6FF),
      textPrimary: Color(0xFF1E3A8A),
      textSecondary: Color(0xFF2563EB),
    ),
    const LandingPageTheme(
      name: 'glowingNexusPalette',
      category: 'تكنولوجيا / Premium',
      description: 'تصميم عالي التقنية مع إضاءات نيون سيان وظلال عميقة.',
      defaultFont: 'Cairo',
      primary: Color(0xFF00E5FF),
      secondary: Color(0xFF1E3A8A),
      background: Color(0xFF030712),
      textPrimary: Color(0xFFF3F4F6),
      textSecondary: Color(0xFF94A3B8),
    ),
    const LandingPageTheme(
      name: 'Cyber Slate',
      category: 'ألعاب / برمجة',
      description: 'نمط داكن مع إضاءات نيون لمحبي التكنولوجيا الحديثة.',
      defaultFont: 'Oswald',
      primary: Color(0xFF8B5CF6),
      secondary: Color(0xFFD946EF),
      background: Color(0xFF020617),
      textPrimary: Color(0xFFF8FAFC),
      textSecondary: Color(0xFF94A3B8),
    ),
    const LandingPageTheme(
      name: 'Default Dark',
      category: 'عام',
      description: 'النمط الافتراضي الداكن للمنصة.',
      defaultFont: 'Cairo',
      primary: Color(0xFF6366F1),
      secondary: Color(0xFF06B6D4),
      background: Color(0xFF0F172A),
      textPrimary: Color(0xFFF8FAFC),
      textSecondary: Color(0xFF94A3B8),
    ),
    const LandingPageTheme(
      name: 'Professional Blue',
      category: 'شركات / Professional',
      description: 'تصميم رسمي واحترافي يناسب الشركات الكبيرة.',
      primary: Color(0xFF1E3A8A),
      secondary: Color(0xFF3B82F6),
      background: Color(0xFFF8FAFC),
      textPrimary: Color(0xFF0F172A),
      textSecondary: Color(0xFF475569),
      defaultFont: 'Almarai',
    ),
    const LandingPageTheme(
      name: 'Modern Cyan',
      category: 'عصري / Modern',
      description: 'نمط عصري وحيوي للشركات التقنية والناشئة.',
      primary: Color(0xFF0891B2),
      secondary: Color(0xFF22D3EE),
      background: Color(0xFF0F172A),
      textPrimary: Color(0xFFF8FAFC),
      textSecondary: Color(0xFF94A3B8),
      defaultFont: 'Cairo',
    ),
    const LandingPageTheme(
      name: 'Creative Violet',
      category: 'إبداعي / Creative',
      description: 'ألوان جريئة ومبدعة للمصممين والفنانين.',
      primary: Color(0xFF7C3AED),
      secondary: Color(0xFFC084FC),
      background: Color(0xFFFFF7ED),
      textPrimary: Color(0xFF431407),
      textSecondary: Color(0xFF9A3412),
      defaultFont: 'Lalezar',
    ),
    const LandingPageTheme(
      name: 'Minimal Slate',
      category: 'فاخر / Minimal',
      description: 'تصميم بسيط ونظيف يركز على المحتوى.',
      primary: Color(0xFF334155),
      secondary: Color(0xFF64748B),
      background: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF0F172A),
      textSecondary: Color(0xFF64748B),
      defaultFont: 'Tajawal',
    ),
    const LandingPageTheme(
      name: 'Luxury Gold',
      category: 'فاخر / Luxury',
      description: 'مزيج من الذهب والأسود للفخامة المطلقة.',
      primary: Color(0xFF0F172A),
      secondary: Color(0xFFD4AF37),
      background: Color(0xFF020617),
      textPrimary: Color(0xFFF8FAFC),
      textSecondary: Color(0xFFD1D5DB),
      defaultFont: 'Amiri',
    ),
  ];
}
